// Standardized expense categories — single source of truth for Expenses and Budgets.
export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Groceries',
  'Transport',
  'Fuel',
  'Utilities',
  'Rent',
  'Mortgage',
  'Internet',
  'Phone',
  'Insurance',
  'Healthcare',
  'Education',
  'Childcare',
  'Entertainment',
  'Subscriptions',
  'Shopping',
  'Clothing',
  'Personal Care',
  'Gifts',
  'Donations',
  'Travel',
  'Hotels',
  'Taxes',
  'Fees & Charges',
  'Savings',
  'Investments',
  'Business',
  'Office',
  'Software',
  'Income',
  'Other',
] as const;

export type ExpenseCategory = typeof EXPENSE_CATEGORIES[number];
