project_id = "svixhxkbroelwmpxynjy"

[functions.admin-stepup]
verify_jwt = true

[functions.admin-check]
verify_jwt = true

[functions.send-contact-message]
verify_jwt = false

[functions.ai-usage-check]
verify_jwt = false
